import type { ElementType } from './types';

export interface BestiaryEntry {
  id: string;
  name: string;
  title: string;
  category: 'common' | 'zone_boss' | 'dungeon_boss' | 'hidden_boss';
  element: ElementType;
  weakness: ElementType;
  zone: string;
  artSrc: string;
  icon: string;
  lore: string;
  baseHp: number;
  baseDmg: number;
}

export const BESTIARY_CATALOG: BestiaryEntry[] = [
  // ==================== 1. COMMON MONSTER FAMILIES ====================
  {
    id: 'slime',
    name: 'Ядовитый Слизень',
    title: 'Кислотная Амёба',
    category: 'common',
    element: 'poison',
    weakness: 'fire',
    zone: 'Зелёные Холмы',
    artSrc: '/monsters/slime.jpg',
    icon: '🟢',
    lore: 'Простейшая, но коварная протоплазма. Выделяет едкую кислоту, разъедающую экипировку.',
    baseHp: 320,
    baseDmg: 35,
  },
  {
    id: 'rat',
    name: 'Чумной Крысолюд',
    title: 'Падальщик Сточных Труб',
    category: 'common',
    element: 'poison',
    weakness: 'fire',
    zone: 'Заброшенная Шахта',
    artSrc: '/monsters/rat.jpg',
    icon: '🐀',
    lore: 'Мутировавший под воздействием ядовитых испарений зверь. Атакует стаями из темноты.',
    baseHp: 400,
    baseDmg: 45,
  },
  {
    id: 'goblin',
    name: 'Лесной Гоблин',
    title: 'Коварный Налётчик',
    category: 'common',
    element: 'physical',
    weakness: 'fire',
    zone: 'Зелёные Холмы / Тёмный Лес',
    artSrc: '/monsters/goblin.jpg',
    icon: '👺',
    lore: 'Хитрые разбойники, устраивающие засады на торговых трактах. Вооружены зазубренными кинжалами.',
    baseHp: 480,
    baseDmg: 52,
  },
  {
    id: 'skeleton',
    name: 'Скелет-Воин',
    title: 'Восставший Мертвец',
    category: 'common',
    element: 'dark',
    weakness: 'holy',
    zone: 'Катакомбы / Шахта',
    artSrc: '/monsters/skeleton.jpg',
    icon: '💀',
    lore: 'Останки древних воинов, поднятые некромантией. Не ведают страха, усталости и боли.',
    baseHp: 580,
    baseDmg: 64,
  },
  {
    id: 'zombie',
    name: 'Гниющий Зомби',
    title: 'Ходячий Труп',
    category: 'common',
    element: 'poison',
    weakness: 'fire',
    zone: 'Гнилые Болота',
    artSrc: '/monsters/zombie.jpg',
    icon: '🧟',
    lore: 'Разлагающееся тело, движимое ненасытным голодом. Переносит смертоносную болотную заразу.',
    baseHp: 750,
    baseDmg: 58,
  },
  {
    id: 'spider',
    name: 'Пещерный Паук',
    title: 'Охотник Тенетов',
    category: 'common',
    element: 'poison',
    weakness: 'ice',
    zone: 'Тёмный Лес / Болота',
    artSrc: '/monsters/spider.jpg',
    icon: '🕷️',
    lore: 'Огромный хищник с парализующим ядом. Плетёт паутину, способную удержать даже могучего воина.',
    baseHp: 620,
    baseDmg: 72,
  },
  {
    id: 'wolf',
    name: 'Сумрачный Волк',
    title: 'Хищник Ночи',
    category: 'common',
    element: 'physical',
    weakness: 'fire',
    zone: 'Тёмный Лес',
    artSrc: '/monsters/wolf.jpg',
    icon: '🐺',
    lore: 'Быстрый и безжалостный хищник чащобы. Его вой вселяет первобытный ужас в сердца путников.',
    baseHp: 680,
    baseDmg: 80,
  },
  {
    id: 'orc',
    name: 'Орк-Крушитель',
    title: 'Воин Кровавой Орды',
    category: 'common',
    element: 'fire',
    weakness: 'ice',
    zone: 'Жерло Бездны / Холмы',
    artSrc: '/monsters/orc.jpg',
    icon: '👹',
    lore: 'Свирепый воин пустошей, закалённый в бесконечных войнах. Сокрушает любые латы тяжелым топором.',
    baseHp: 950,
    baseDmg: 95,
  },
  {
    id: 'bandit',
    name: 'Разбойник Пустошей',
    title: 'Наёмный Головорез',
    category: 'common',
    element: 'physical',
    weakness: 'lightning',
    zone: 'Палящие Пески',
    artSrc: '/monsters/bandit.jpg',
    icon: '🥷',
    lore: 'Отчаявшийся изгнанник, грабящий караваны ради наживы. Быстро наносит колющие удары.',
    baseHp: 720,
    baseDmg: 88,
  },
  {
    id: 'ghost',
    name: 'Скорбящий Призрак',
    title: 'Бестелесный Дух',
    category: 'common',
    element: 'ice',
    weakness: 'holy',
    zone: 'Катакомбы / Замок',
    artSrc: '/monsters/ghost.jpg',
    icon: '👻',
    lore: 'Душа погибшего, застрявшая между мирами. Проходит сквозь физическую броню ледяным касанием.',
    baseHp: 800,
    baseDmg: 92,
  },
  {
    id: 'vampire',
    name: 'Кровопийца Ночи',
    title: 'Аристократ Тьмы',
    category: 'common',
    element: 'dark',
    weakness: 'holy',
    zone: 'Замок Проклятых',
    artSrc: '/monsters/vampire.jpg',
    icon: '🧛',
    lore: 'Древнее ночное создание, питающееся жизненной силой смертных. Восстанавливает здоровье от укусов.',
    baseHp: 1100,
    baseDmg: 115,
  },
  {
    id: 'golem',
    name: 'Каменный Голем',
    title: 'Охранный Страж',
    category: 'common',
    element: 'physical',
    weakness: 'lightning',
    zone: 'Заброшенная Шахта',
    artSrc: '/monsters/golem.jpg',
    icon: '🗿',
    lore: 'Массивный монолит из горной породы, оживленный рунической магией гномов.',
    baseHp: 1600,
    baseDmg: 85,
  },
  {
    id: 'cultist',
    name: 'Фанатик Культа',
    title: 'Служитель Забвения',
    category: 'common',
    element: 'dark',
    weakness: 'holy',
    zone: 'Катакомбы',
    artSrc: '/monsters/cultist.jpg',
    icon: '🕯️',
    lore: 'Обезумевший сектант, призывающий древнее зло. Использует тёмные проклятия и жертвенные ритуалы.',
    baseHp: 850,
    baseDmg: 105,
  },
  {
    id: 'demon',
    name: 'Адский Бес',
    title: 'Исчадие Преисподней',
    category: 'common',
    element: 'fire',
    weakness: 'ice',
    zone: 'Жерло Бездны',
    artSrc: '/monsters/demon.jpg',
    icon: '😈',
    lore: 'Огненное порождение лавовых глубин, жаждущее испепелить всё живое на поверхности.',
    baseHp: 1250,
    baseDmg: 130,
  },
  {
    id: 'elemental_fire',
    name: 'Элементаль Огня',
    title: 'Живой Очаг Пламени',
    category: 'common',
    element: 'fire',
    weakness: 'ice',
    zone: 'Палящие Пески / Вулкан',
    artSrc: '/monsters/fire_elemental.jpg',
    icon: '🔥',
    lore: 'Сгусток первородного яростного огня. Поджигает противников каждым соприкосновением.',
    baseHp: 1300,
    baseDmg: 140,
  },
  {
    id: 'elemental_ice',
    name: 'Элементаль Льда',
    title: 'Дух Вечной Мерзлоты',
    category: 'common',
    element: 'ice',
    weakness: 'fire',
    zone: 'Ледяные Пики',
    artSrc: '/monsters/elemental_ice.jpg',
    icon: '❄️',
    lore: 'Ледяной кристаллический фантом, замораживающий кровь в жилах и замедляющий атаки.',
    baseHp: 1450,
    baseDmg: 125,
  },
  {
    id: 'elemental_storm',
    name: 'Элементаль Бури',
    title: 'Ярость Грозы',
    category: 'common',
    element: 'lightning',
    weakness: 'physical',
    zone: 'Бездна Океана / Астрал',
    artSrc: '/monsters/storm_elemental.jpg',
    icon: '⚡',
    lore: 'Вихрь концентрированной электрической энергии, разящий смертоносными дуговыми разрядами.',
    baseHp: 1380,
    baseDmg: 155,
  },
  {
    id: 'mushroom',
    name: 'Гриб-Споровик',
    title: 'Токсичный Мутант',
    category: 'common',
    element: 'poison',
    weakness: 'fire',
    zone: 'Зелёные Холмы',
    artSrc: '/monsters/mushroom.jpg',
    icon: '🍄',
    lore: 'Опасный грибной симбиот, распыляющий облака ядовитых галлюциногенных спор.',
    baseHp: 520,
    baseDmg: 48,
  },
  {
    id: 'crab',
    name: 'Глубинный Панцирник',
    title: 'Бронированный Краб',
    category: 'common',
    element: 'ice',
    weakness: 'lightning',
    zone: 'Бездна Океана',
    artSrc: '/monsters/crab.jpg',
    icon: '🦀',
    lore: 'Морской обитатель с панцирем прочнее закалённой стали и сокрушительными клешнями.',
    baseHp: 1750,
    baseDmg: 98,
  },
  {
    id: 'snake',
    name: 'Болотная Кобра',
    title: 'Ядовитый Аспид',
    category: 'common',
    element: 'poison',
    weakness: 'ice',
    zone: 'Гнилые Болота',
    artSrc: '/monsters/snake.jpg',
    icon: '🐍',
    lore: 'Молниеносная рептилия, наносящая смертоносные укусы из густых болотных зарослей.',
    baseHp: 780,
    baseDmg: 110,
  },
  {
    id: 'scorpion',
    name: 'Песчаный Скорпион',
    title: 'Жало Дюн',
    category: 'common',
    element: 'poison',
    weakness: 'ice',
    zone: 'Палящие Пески',
    artSrc: '/monsters/scorpion.jpg',
    icon: '🦂',
    lore: 'Гигантский скорпион, скрывающийся под слоем песка в ожидании зазевавшихся путников.',
    baseHp: 920,
    baseDmg: 125,
  },
  {
    id: 'harpy',
    name: 'Свирепая Гарпия',
    title: 'Крылатая Хищница',
    category: 'common',
    element: 'lightning',
    weakness: 'physical',
    zone: 'Гнилые Болота / Пики',
    artSrc: '/monsters/harpy.jpg',
    icon: '🦅',
    lore: 'Полуженщина-полуптица, пикирующая с высоты и раздирающая жертву стальными когтями.',
    baseHp: 860,
    baseDmg: 135,
  },
  {
    id: 'bear',
    name: 'Пещерный Медведь',
    title: 'Хозяин Тайги',
    category: 'common',
    element: 'physical',
    weakness: 'fire',
    zone: 'Тёмный Лес / Пики',
    artSrc: '/monsters/bear.jpg',
    icon: '🐻',
    lore: 'Массивный зверь невероятной физической силы, впадающий в ярость при виде врагов.',
    baseHp: 1850,
    baseDmg: 120,
  },
  {
    id: 'mimic',
    name: 'Золотой Мимик',
    title: 'Ловушка Жадных',
    category: 'common',
    element: 'dark',
    weakness: 'holy',
    zone: 'Шахта / Сокровищница',
    artSrc: '/monsters/mimic.jpg',
    icon: '📦',
    lore: 'Коварный монстр, маскирующийся под сундук с сокровищами, чтобы внезапно поглотить авантюриста.',
    baseHp: 1400,
    baseDmg: 160,
  },
  {
    id: 'mage',
    name: 'Тёмный Чернокнижник',
    title: 'Мастер Адептов Тьмы',
    category: 'common',
    element: 'dark',
    weakness: 'holy',
    zone: 'Замок Проклятых',
    artSrc: '/monsters/dark_mage.jpg',
    icon: '🧙‍♂️',
    lore: 'Предавший свет маг, овладевший запретными заклинаниями Бездны и гравитации.',
    baseHp: 1150,
    baseDmg: 180,
  },
  {
    id: 'knight',
    name: 'Падший Рыцарь',
    title: 'Страж Чёрного Ордена',
    category: 'common',
    element: 'physical',
    weakness: 'holy',
    zone: 'Замок Проклятых',
    artSrc: '/monsters/knight.jpg',
    icon: '🛡️',
    lore: 'Элитный воин в тяжелых зачарованных доспехах, присягнувший силам вечного мрака.',
    baseHp: 2100,
    baseDmg: 145,
  },
  {
    id: 'dragon',
    name: 'Красный Дракон',
    title: 'Владыка Небесного Огня',
    category: 'common',
    element: 'fire',
    weakness: 'ice',
    zone: 'Жерло Бездны / Небесный Престол',
    artSrc: '/monsters/dragon.jpg',
    icon: '🐉',
    lore: 'Величественный ящер, дыхание которого плавит гранит и сжигает целые армии.',
    baseHp: 3800,
    baseDmg: 260,
  },
  {
    id: 'wisp',
    name: 'Астральный Огонёк',
    title: 'Дух Забытого Света',
    category: 'common',
    element: 'holy',
    weakness: 'dark',
    zone: 'Зелёные Холмы / Астрал',
    artSrc: '/monsters/wisp.jpg',
    icon: '✨',
    lore: 'Светящийся эфирный сгусток, излучающий священную энергию древних богов.',
    baseHp: 700,
    baseDmg: 110,
  },
  {
    id: 'construct',
    name: 'Рунический Автоматон',
    title: 'Механический Страж',
    category: 'common',
    element: 'lightning',
    weakness: 'physical',
    zone: 'Астральный Разлом',
    artSrc: '/monsters/construct.jpg',
    icon: '🤖',
    lore: 'Древний боевой робот на эфирных кристаллах, продолжающий выполнять приказ своих создателей.',
    baseHp: 2200,
    baseDmg: 170,
  },
  {
    id: 'abyss',
    name: 'Порождение Бездны',
    title: 'Тварь Пустоты',
    category: 'common',
    element: 'dark',
    weakness: 'holy',
    zone: 'Ядро Бездны',
    artSrc: '/monsters/abyss.jpg',
    icon: '🌑',
    lore: 'Искажённая космическая материя, поглощающая свет, тепло и надежду.',
    baseHp: 3100,
    baseDmg: 230,
  },

  // ==================== 2. ZONE BOSSES (16 BOSSES) ====================
  {
    id: 'boss_goblin_king',
    name: 'Король Гоблинов Гнус',
    title: 'Самопровозглашённый Монарх Чащи',
    category: 'zone_boss',
    element: 'physical',
    weakness: 'fire',
    zone: 'Зелёные Холмы (Этап 10)',
    artSrc: '/monsters/goblin_king.jpg',
    icon: '👑',
    lore: 'Верховный вождь всех гоблинских кланов долины. Вооружен зазубренным золотым ятаганом.',
    baseHp: 4200,
    baseDmg: 180,
  },
  {
    id: 'boss_spider_queen',
    name: 'Арахна Матка',
    title: 'Королева Ядовитой Чащи',
    category: 'zone_boss',
    element: 'poison',
    weakness: 'fire',
    zone: 'Тёмный Лес (Этап 10)',
    artSrc: '/monsters/spider_queen.jpg',
    icon: '🕷️',
    lore: 'Древняя прародительница пауков, опутавшая паутиной половину континента.',
    baseHp: 5800,
    baseDmg: 240,
  },
  {
    id: 'boss_golem_grak',
    name: 'Каменный Голем Грак',
    title: 'Сердце Гномьих Шахт',
    category: 'zone_boss',
    element: 'physical',
    weakness: 'lightning',
    zone: 'Заброшенная Шахта (Этап 10)',
    artSrc: '/monsters/golem.jpg',
    icon: '🗿',
    lore: 'Титанический страж, высеченный из адамантитовой руды для защиты ядра шахты.',
    baseHp: 8500,
    baseDmg: 280,
  },
  {
    id: 'boss_varatrax',
    name: 'Болотный Варатракс',
    title: 'Ужас Мёртвых Топей',
    category: 'zone_boss',
    element: 'poison',
    weakness: 'ice',
    zone: 'Гнилые Болота (Этап 10)',
    artSrc: '/monsters/hydra.jpg',
    icon: '🐊',
    lore: 'Многоглавый змей глубин, отравляющий воздух ядовитым туманом на мили вокруг.',
    baseHp: 11000,
    baseDmg: 340,
  },
  {
    id: 'boss_iblis',
    name: 'Султан Песков Иблис',
    title: 'Повелитель Бурь и Миражей',
    category: 'zone_boss',
    element: 'fire',
    weakness: 'ice',
    zone: 'Палящие Пески (Этап 10)',
    artSrc: '/monsters/djinn.jpg',
    icon: '🧞',
    lore: 'Древний джинн огня, заточенный в золотой сосуд и освобожденный для мести смертным.',
    baseHp: 14500,
    baseDmg: 420,
  },
  {
    id: 'boss_magmus',
    name: 'Лорд Пламени Магмус',
    title: 'Владыка Лавового Сердца',
    category: 'zone_boss',
    element: 'fire',
    weakness: 'ice',
    zone: 'Жерло Бездны (Этап 10)',
    artSrc: '/monsters/ifrit.jpg',
    icon: '👹',
    lore: 'Архидемон преисподней, купающийся в расплавленной магме и призывающий метеоритный град.',
    baseHp: 19000,
    baseDmg: 520,
  },
  {
    id: 'boss_moroz',
    name: 'Владыка Метелей Мороз',
    title: 'Вечный Император Льда',
    category: 'zone_boss',
    element: 'ice',
    weakness: 'fire',
    zone: 'Ледяные Пики (Этап 10)',
    artSrc: '/monsters/yeti.jpg',
    icon: '❄️',
    lore: 'Холодный властелин вершин, способный обратить любое живое существо в ледяную статую.',
    baseHp: 24000,
    baseDmg: 610,
  },
  {
    id: 'boss_malzahar',
    name: 'Архилич Малзахар',
    title: 'Хранитель Чёрного Фолианта',
    category: 'zone_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Подземные Катакомбы (Этап 10)',
    artSrc: '/monsters/lich.jpg',
    icon: '🧙‍♂️',
    lore: 'Бессмертный чародей, разорвавший связь своей души с телом ради абсолютного господства.',
    baseHp: 31000,
    baseDmg: 740,
  },
  {
    id: 'boss_dracula',
    name: 'Граф Дракула',
    title: 'Патриарх Кровавой Ночи',
    category: 'zone_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Замок Проклятых (Этап 10)',
    artSrc: '/monsters/vampire.jpg',
    icon: '🧛‍♂️',
    lore: 'Первый среди вампиров, правящий замком из алого мрамора уже более тысячи лет.',
    baseHp: 39000,
    baseDmg: 890,
  },
  {
    id: 'boss_kraken',
    name: 'Кракен Глубин',
    title: 'Пожиратель Кораблей',
    category: 'zone_boss',
    element: 'ice',
    weakness: 'lightning',
    zone: 'Бездна Океана (Этап 10)',
    artSrc: '/monsters/kraken.jpg',
    icon: '🦑',
    lore: 'Титанический спрут океанского дна, чьи щупальца вызывают сокрушительные цунами.',
    baseHp: 48000,
    baseDmg: 1050,
  },
  {
    id: 'boss_architect',
    name: 'Архитектор Измерений',
    title: 'Хранитель Реальности',
    category: 'zone_boss',
    element: 'lightning',
    weakness: 'dark',
    zone: 'Астральный Разлом (Этап 10)',
    artSrc: '/monsters/beholder.jpg',
    icon: '👁️',
    lore: 'Высший космический разум, манипулирующий временем, пространством и гравитацией.',
    baseHp: 62000,
    baseDmg: 1320,
  },
  {
    id: 'boss_abaddon',
    name: 'Владыка Бездны Абаддон',
    title: 'Начало Конца Времён',
    category: 'zone_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Ядро Бездны (Этап 10)',
    artSrc: '/monsters/abyss.jpg',
    icon: '🌑',
    lore: 'Воплощение первозданной энтропии, уничтожающее целые звездные системы.',
    baseHp: 85000,
    baseDmg: 1750,
  },

  // ==================== 3. HIDDEN SECRET BOSSES ====================
  {
    id: 'boss_yggdrasil',
    name: 'Древо Жизни Иггдрасиль',
    title: 'Сердце Эдемского Сада',
    category: 'hidden_boss',
    element: 'poison',
    weakness: 'fire',
    zone: 'Эдемский Сад (Скрытая)',
    artSrc: '/monsters/treant.jpg',
    icon: '🌳',
    lore: 'Исполинское древо миров, корни которого питают саму ткань мироздания.',
    baseHp: 55000,
    baseDmg: 1100,
  },
  {
    id: 'boss_aurum',
    name: 'Золотой Дракон Аурум',
    title: 'Хранитель Сокровищницы',
    category: 'hidden_boss',
    element: 'holy',
    weakness: 'dark',
    zone: 'Сокровищница Гномов (Скрытая)',
    artSrc: '/monsters/dragon.jpg',
    icon: '🐉',
    lore: 'Дракон с чешуей из чистейшего орихалка, стерегущий несметные богатства предков.',
    baseHp: 78000,
    baseDmg: 1500,
  },
  {
    id: 'boss_nyarlathotep',
    name: 'Бог Хаоса Ньярлатхотеп',
    title: 'Ползучий Хаос',
    category: 'hidden_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Цитадель Хаоса (Скрытая)',
    artSrc: '/monsters/abyss.jpg',
    icon: '🦑',
    lore: 'Древний бог тысячи ликов, сводящий с ума смертных одним лишь своим присутствием.',
    baseHp: 110000,
    baseDmg: 2100,
  },
  {
    id: 'boss_creator',
    name: 'Творец Вселенной',
    title: 'Абсолютный Бог Сущего',
    category: 'hidden_boss',
    element: 'holy',
    weakness: 'dark',
    zone: 'Небесный Престол (Скрытая)',
    artSrc: '/monsters/titan.jpg',
    icon: '🌟',
    lore: 'Создатель миров и времени, венчающий вершину бытия. Финальный вызов сильнейшим героям.',
    baseHp: 180000,
    baseDmg: 3200,
  },

  // ==================== 4. DUNGEON BOSSES ====================
  {
    id: 'dungeon_slime',
    name: 'Король Слаймов',
    title: 'Владыка Склизкого Логова',
    category: 'dungeon_boss',
    element: 'poison',
    weakness: 'fire',
    zone: 'Подземелье: Склизкое Логово',
    artSrc: '/monsters/slime_king.jpg',
    icon: '👑',
    lore: 'Колоссальный сгусток кислоты, вобравший магические отходы со всего королевства.',
    baseHp: 6500,
    baseDmg: 210,
  },
  {
    id: 'dungeon_spider',
    name: 'Королева Арахнидов',
    title: 'Хозяйка Паучьего Гнезда',
    category: 'dungeon_boss',
    element: 'poison',
    weakness: 'fire',
    zone: 'Подземелье: Паучье Гнездо',
    artSrc: '/monsters/spider_queen.jpg',
    icon: '🕷️',
    lore: 'Свирепая матка, защищающая выводок сотен ядовитых паучат ценой своей жизни.',
    baseHp: 12000,
    baseDmg: 380,
  },
  {
    id: 'dungeon_skeleton',
    name: 'Владыка Скелетов',
    title: 'Повелитель Крипты Костей',
    category: 'dungeon_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Подземелье: Крипта Костей',
    artSrc: '/monsters/skeleton_king.jpg',
    icon: '💀',
    lore: 'Древний военачальник мертвецов, чья корона излучает смертоносное астральное сияние.',
    baseHp: 22000,
    baseDmg: 580,
  },
  {
    id: 'dungeon_ifrit',
    name: 'Демонический Ифрит',
    title: 'Страж Обители Огня',
    category: 'dungeon_boss',
    element: 'fire',
    weakness: 'ice',
    zone: 'Подземелье: Обитель Огня',
    artSrc: '/monsters/ifrit.jpg',
    icon: '🔥',
    lore: 'Двуногий элементаль адского пекла, превращающий оружие героев в пепел.',
    baseHp: 38000,
    baseDmg: 820,
  },
  {
    id: 'dungeon_archmage',
    name: 'Тёмный Архимаг',
    title: 'Владыка Башни Мага',
    category: 'dungeon_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Подземелье: Башня Мага',
    artSrc: '/monsters/dark_mage.jpg',
    icon: '🔮',
    lore: 'Чародей, постигший тайны искажения материи и защищаемый магическими сферами.',
    baseHp: 56000,
    baseDmg: 1150,
  },
  {
    id: 'dungeon_vampire',
    name: 'Кровавый Дракула',
    title: 'Хозяин Гробницы Вампира',
    category: 'dungeon_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Подземелье: Гробница Вампира',
    artSrc: '/monsters/vampire.jpg',
    icon: '🦇',
    lore: 'Высший аристократ ночи, черпающий бессмертие из вековых склепов предков.',
    baseHp: 82000,
    baseDmg: 1600,
  },
  {
    id: 'dungeon_void',
    name: 'Породитель Тьмы',
    title: 'Ужас Разлома Бездны',
    category: 'dungeon_boss',
    element: 'dark',
    weakness: 'holy',
    zone: 'Подземелье: Разлом Бездны',
    artSrc: '/monsters/abyss.jpg',
    icon: '👁️',
    lore: 'Многоглазое хтоническое божество, искривляющее законы мироздания.',
    baseHp: 120000,
    baseDmg: 2300,
  },
  {
    id: 'dungeon_titan',
    name: 'Верховный Титан',
    title: 'Хранитель Святилища Богов',
    category: 'dungeon_boss',
    element: 'holy',
    weakness: 'dark',
    zone: 'Подземелье: Святилище Богов',
    artSrc: '/monsters/titan.jpg',
    icon: '🌟',
    lore: 'Исполин небесной кузницы, обладающий непоколебимой силой божественного грома.',
    baseHp: 200000,
    baseDmg: 3600,
  },
];

export function getBestiaryMasteryTier(killsCount: number): { tier: number; label: string; bonusDmgPct: number; bonusDefPct: number; nextNeeded: number } {
  if (killsCount >= 100) {
    return { tier: 3, label: '★3 Магистр Охоты (+15% Урона, +10% Защиты)', bonusDmgPct: 15, bonusDefPct: 10, nextNeeded: 100 };
  }
  if (killsCount >= 40) {
    return { tier: 2, label: '★2 Истребитель (+8% Урона, +5% Защиты)', bonusDmgPct: 8, bonusDefPct: 5, nextNeeded: 100 };
  }
  if (killsCount >= 10) {
    return { tier: 1, label: '★1 Следопыт (+3% Урона, +2% Защиты)', bonusDmgPct: 3, bonusDefPct: 2, nextNeeded: 40 };
  }
  return { tier: 0, label: 'Новичок (Нет бонусов, нужно ещё 10 убийств)', bonusDmgPct: 0, bonusDefPct: 0, nextNeeded: 10 };
}

export const getHuntingMasteryRank = getBestiaryMasteryTier;

