import type { AscendancyConstellation, CosmeticWing } from './types';

export const WINGS_CATALOG: CosmeticWing[] = [
  {
    id: 'wing_archangel',
    name: 'Крылья Серафима',
    icon: '🪽',
    desc: 'Шестикрылое сияние небесного архангела со священным ореолом.',
    rarity: 'legendary',
    auraColor: '#facc15',
    bonusDmgPct: 15,
    bonusHpPct: 20,
    bonusSpeedPct: 10,
    unlocked: true,
    costGold: 50000,
  },
  {
    id: 'wing_demon',
    name: 'Пылающие Крылья Архидемона',
    icon: '🔥',
    desc: 'Исполинские демонические крылья из адского пламени с лавовыми жилами.',
    rarity: 'mythic',
    auraColor: '#ef4444',
    bonusDmgPct: 30,
    bonusHpPct: 15,
    bonusSpeedPct: 15,
    unlocked: false,
    costGold: 250000,
  },
  {
    id: 'wing_void',
    name: 'Астральные Крылья Бездны',
    icon: '🌌',
    desc: 'Первозданная космическая сингулярность с фиолетово-лазурными частицами.',
    rarity: 'divine',
    auraColor: '#c084fc',
    bonusDmgPct: 50,
    bonusHpPct: 40,
    bonusSpeedPct: 25,
    unlocked: false,
    costGold: 1000000,
    costShards: 500,
  },
  {
    id: 'wing_phoenix',
    name: 'Солнечные Крылья Феникса',
    icon: '🦅',
    desc: 'Бессмертное оперение возрождающегося феникса с золотым пламенем.',
    rarity: 'mythic',
    auraColor: '#f97316',
    bonusDmgPct: 35,
    bonusHpPct: 25,
    bonusSpeedPct: 20,
    unlocked: false,
    costGold: 500000,
    costShards: 250,
  },
  {
    id: 'wing_frost',
    name: 'Ледяные Крылья Валькирии',
    icon: '❄️',
    desc: 'Кристаллическое сияние вечной мерзлоты и северного сияния.',
    rarity: 'legendary',
    auraColor: '#38bdf8',
    bonusDmgPct: 20,
    bonusHpPct: 30,
    bonusSpeedPct: 15,
    unlocked: false,
    costGold: 350000,
  },
  {
    id: 'wing_dragon_king',
    name: 'Крылья Драконьего Императора',
    icon: '🐉',
    desc: 'Исполинские драконьи крылья с мерцающей чешуей и аурой господства.',
    rarity: 'divine',
    auraColor: '#dc2626',
    bonusDmgPct: 60,
    bonusHpPct: 50,
    bonusSpeedPct: 30,
    unlocked: false,
    costGold: 2000000,
    costShards: 800,
  },
  {
    id: 'wing_cosmic_god',
    name: 'Крылья Архитектора Мироздания',
    icon: '🌟',
    desc: 'Чистая энергия сотворения галактик с вращающимися квазарами.',
    rarity: 'divine',
    auraColor: '#e0e7ff',
    bonusDmgPct: 80,
    bonusHpPct: 60,
    bonusSpeedPct: 40,
    unlocked: false,
    costGold: 5000000,
    costShards: 1500,
  },
];

export const ASCENDANCY_CONSTELLATIONS: AscendancyConstellation[] = [
  {
    id: 'asc_might',
    name: 'Созвездие Титана',
    icon: '⚔️',
    desc: '+10% к общему урону героя за уровень созвездия.',
    level: 0,
    maxLevel: 30,
    costPerLevel: 50,
    stat: 'playerAtk',
    valuePerLevel: 10,
  },
  {
    id: 'asc_immortal',
    name: 'Созвездие Вечности',
    icon: '🛡️',
    desc: '+12% к максимальному запасу здоровья за уровень.',
    level: 0,
    maxLevel: 30,
    costPerLevel: 50,
    stat: 'maxHp',
    valuePerLevel: 12,
  },
  {
    id: 'asc_swiftness',
    name: 'Созвездие Кометы',
    icon: '⚡',
    desc: '+5% к скорости атак и применения способностей.',
    level: 0,
    maxLevel: 30,
    costPerLevel: 60,
    stat: 'attackSpeed',
    valuePerLevel: 5,
  },
  {
    id: 'asc_fortune',
    name: 'Созвездие Золотого Дракона',
    icon: '💰',
    desc: '+20% к выпадающему золоту и +15% к опыту за уровень.',
    level: 0,
    maxLevel: 30,
    costPerLevel: 45,
    stat: 'goldBonusPct',
    valuePerLevel: 20,
  },
  {
    id: 'asc_crit',
    name: 'Созвездие Сверхновой',
    icon: '💥',
    desc: '+4% к шансу критического удара и +20% к силе критического урона.',
    level: 0,
    maxLevel: 30,
    costPerLevel: 75,
    stat: 'critChance',
    valuePerLevel: 4,
  },
  {
    id: 'asc_vampire',
    name: 'Созвездие Алой Луны',
    icon: '🩸',
    desc: '+3% похищения жизни при каждом ударе за уровень созвездия.',
    level: 0,
    maxLevel: 30,
    costPerLevel: 80,
    stat: 'lifestealPct',
    valuePerLevel: 3,
  },
];
