import type { TarotCard } from './types';

export const TAROT_DECK: TarotCard[] = [
  {
    id: 'tarot_fool',
    name: '0. Шут (Дурак)',
    arcana: 'Старший Аркан',
    icon: '🃏',
    desc: 'Дарует случайное благословение или неожиданный взрыв критической мощи.',
    color: '#38bdf8',
    effect: 'random_blessing',
    effectValue: 50,
  },
  {
    id: 'tarot_magician',
    name: 'I. Маг',
    arcana: 'Старший Аркан',
    icon: '🧙‍♂️',
    desc: 'Увеличивает урон всех магических способностей на +80% на 30 секунд.',
    color: '#818cf8',
    effect: 'spell_power',
    effectValue: 80,
  },
  {
    id: 'tarot_priestess',
    name: 'II. Верховная Жрица',
    arcana: 'Старший Аркан',
    icon: '🔮',
    desc: 'Дарует бесконечную ману и моментальную перезарядку умений на 20 секунд.',
    color: '#c084fc',
    effect: 'mana_surge',
    effectValue: 100,
  },
  {
    id: 'tarot_empress',
    name: 'III. Императрица',
    arcana: 'Старший Аркан',
    icon: '👑',
    desc: 'Удваивает выпадение всех трав, руды и золота на 1 минуту.',
    color: '#4ade80',
    effect: 'double_drops',
    effectValue: 100,
  },
  {
    id: 'tarot_emperor',
    name: 'IV. Император',
    arcana: 'Старший Аркан',
    icon: '👑',
    desc: 'Дарует абсолютный барьер неуязвимости на 10 секунд.',
    color: '#f97316',
    effect: 'invulnerability',
    effectValue: 10,
  },
  {
    id: 'tarot_hierophant',
    name: 'V. Иерофант',
    arcana: 'Старший Аркан',
    icon: '📿',
    desc: 'Увеличивает получаемый опыт со всех монстров на +150% на 2 минуты.',
    color: '#facc15',
    effect: 'xp_boost',
    effectValue: 150,
  },
  {
    id: 'tarot_lovers',
    name: 'VI. Влюблённые',
    arcana: 'Старший Аркан',
    icon: '💖',
    desc: 'Призывает могучего духа-защитника, исцеляющего героя и атакующего врагов.',
    color: '#f43f5e',
    effect: 'summon_guardian',
    effectValue: 100,
  },
  {
    id: 'tarot_chariot',
    name: 'VII. Колесница',
    arcana: 'Старший Аркан',
    icon: '🏎️',
    desc: 'Увеличивает скорость атак и скорость передвижения героя на +100%.',
    color: '#fb923c',
    effect: 'speed_frenzy',
    effectValue: 100,
  },
  {
    id: 'tarot_strength',
    name: 'VIII. Сила',
    arcana: 'Старший Аркан',
    icon: '🦁',
    desc: '+120% к физическому урону и сокрушительный пробой любой брони.',
    color: '#ea580c',
    effect: 'physical_might',
    effectValue: 120,
  },
  {
    id: 'tarot_hermit',
    name: 'IX. Отшельник',
    arcana: 'Старший Аркан',
    icon: '🕯️',
    desc: 'Окутывает героя туманом скрытности, повышая уклонение до 80%.',
    color: '#94a3b8',
    effect: 'dodge_veil',
    effectValue: 80,
  },
  {
    id: 'tarot_wheel',
    name: 'X. Колесо Фортуны',
    arcana: 'Старший Аркан',
    icon: '🎡',
    desc: 'Утраивает добычу золота и снаряжения за победу над следующими 10 монстрами.',
    color: '#facc15',
    effect: 'double_rewards',
    effectValue: 3,
  },
  {
    id: 'tarot_justice',
    name: 'XI. Справедливость',
    arcana: 'Старший Аркан',
    icon: '⚖️',
    desc: 'Отражает 100% полученного урона обратно во врагов в течение 15 секунд.',
    color: '#e0e7ff',
    effect: 'damage_reflect',
    effectValue: 100,
  },
  {
    id: 'tarot_hanged',
    name: 'XII. Повешенный',
    arcana: 'Старший Аркан',
    icon: '🪢',
    desc: 'Жертвует 20% текущего здоровья, чтобы нанести десятикратный урон по боссу.',
    color: '#a855f7',
    effect: 'blood_sacrifice',
    effectValue: 10,
  },
  {
    id: 'tarot_death',
    name: 'XIII. Смерть',
    arcana: 'Старший Аркан',
    icon: '💀',
    desc: 'Мгновенно сносит 40% от текущего здоровья любого босса или монстра.',
    color: '#a855f7',
    effect: 'boss_smite',
    effectValue: 40,
  },
  {
    id: 'tarot_temperance',
    name: 'XIV. Умеренность',
    arcana: 'Старший Аркан',
    icon: '🏺',
    desc: 'Плавно восстанавливает 10% здоровья и маны каждую секунду в течение 20 секунд.',
    color: '#06b6d4',
    effect: 'regen_aura',
    effectValue: 10,
  },
  {
    id: 'tarot_devil',
    name: 'XV. Дьявол',
    arcana: 'Старший Аркан',
    icon: '😈',
    desc: '+200% к урону и 35% вампиризма, но блокирует использование щитов на 30 секунд.',
    color: '#dc2626',
    effect: 'demonic_frenzy',
    effectValue: 200,
  },
  {
    id: 'tarot_tower',
    name: 'XVI. Башня',
    arcana: 'Старший Аркан',
    icon: '⚡',
    desc: 'Призывает сокрушительный метеоритный шквал, разрывающий броню врага на 70%.',
    color: '#ef4444',
    effect: 'meteor_storm',
    effectValue: 70,
  },
  {
    id: 'tarot_star',
    name: 'XVII. Звезда',
    arcana: 'Старший Аркан',
    icon: '⭐',
    desc: 'Повышает шанс выпадения легендарных, мифических и божественных предметов на +300%.',
    color: '#fef08a',
    effect: 'loot_blessing',
    effectValue: 300,
  },
  {
    id: 'tarot_moon',
    name: 'XVIII. Луна',
    arcana: 'Старший Аркан',
    icon: '🌙',
    desc: 'Следующие 12 атак наносят гарантированный тройной критический урон.',
    color: '#38bdf8',
    effect: 'guaranteed_crits',
    effectValue: 12,
  },
  {
    id: 'tarot_sun',
    name: 'XIX. Солнце',
    arcana: 'Старший Аркан',
    icon: '☀️',
    desc: 'Мгновенно восстанавливает 100% здоровья и маны, нанося святой ослепляющий урон.',
    color: '#fbbf24',
    effect: 'heal_full',
    effectValue: 100,
  },
  {
    id: 'tarot_judgement',
    name: 'XX. Страшный Суд',
    arcana: 'Старший Аркан',
    icon: '📯',
    desc: 'Воскрешает поверженных наёмников и мгновенно уничтожает всех рядовых врагов.',
    color: '#fbbf24',
    effect: 'resurrect_all',
    effectValue: 100,
  },
  {
    id: 'tarot_world',
    name: 'XXI. Мир',
    arcana: 'Старший Аркан',
    icon: '🪐',
    desc: 'Абсолютная гармония: все параметры героя увеличиваются на +100% на 1 минуту.',
    color: '#e0e7ff',
    effect: 'world_harmony',
    effectValue: 100,
  },
];
